application: nu-op-een
version: 1 
runtime: python
api_version: 1

default_expiration: "30d"

handlers:
# html-5 boilerplate redirects from /... to /static/... 
- url: /apple-touch-icon\.png
  mime_type: image/png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml)

- url: /img/(.*\.(gif|png|jpg))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg))
  
- url: /css/(.*\.css)
  mime_type: text/css
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /js/(.*\.js)
  mime_type: text/javascript
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
    
# All other requests go to app.py
- url: /.*
  script: app.py
